services:
  - type: web
    name: bothelp-openai-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
